(() => {
'use strict';
const sourceData=window.Emergence2Catalog,data=sourceData;
if(!data||!Array.isArray(data.episodes))throw new Error('Emergence II content unavailable.');
const list=document.getElementById('episode-list'),reader=document.getElementById('reader'),artIndex=document.getElementById('art-index'),artCaption=document.getElementById('art-caption'),prev=document.getElementById('prev'),next=document.getElementById('next'),close=document.getElementById('emergence2-close'),pageTitle=document.getElementById('page-title'),pageSubtitle=document.getElementById('page-subtitle'),artImage=document.getElementById('chapter-art');
let activeIndex=0;
const faNumber=v=>String(v).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>window.SiteI18n?.getLanguage?.()||'fa';
const catalog=()=>window.SiteI18n?.getCatalog?.()||{};
const label=(key,fallback)=>window.SiteI18n?.get?.(key,fallback)||fallback;
function chapterTitle(){const l=lang();if(l==='fa')return'فصل دوم ظهور';return catalog()?.chapters?.emergence2?.title?.[l]||'Emergence';}
function getLocalizedEpisode(index){const l=lang(),t=catalog()?.chapters?.emergence2?.episodes?.[index];if(!t||l==='fa')return sourceData.episodes[index];return{number:t.number,title:t.title,paragraphs:t.paragraphs||[]};}
function renderReader(ep){const l=lang(),has=ep.paragraphs.length>0,heading='episode-reader-heading',textLabel={fa:'متن قسمت',en:'Episode text',ar:'نص الحلقة',zh:'章节正文'}[l]||'Episode text',prevText={fa:'پیشین',en:'Previous',ar:'السابق',zh:'上一章'}[l]||'Previous',nextText={fa:'پسین',en:'Next',ar:'التالي',zh:'下一章'}[l]||'Next',of={fa:'قسمت '+faNumber(ep.number)+' از '+faNumber(data.total),en:'Episode '+ep.number+' of '+data.total,ar:'الحلقة '+ep.number+' من '+data.total,zh:'第 '+ep.number+' / '+data.total+' 章'}[l]||'';
reader.setAttribute('aria-labelledby',heading);
reader.innerHTML='<header class="reader-head"><div><div class="story-label">'+escapeHtml(chapterTitle())+'</div><h2 id="'+heading+'">'+escapeHtml(ep.title)+'</h2><p>'+escapeHtml(of)+'</p></div></header><section class="block" aria-labelledby="episode-text-heading"><h3 id="episode-text-heading">'+escapeHtml(textLabel)+'</h3>'+(has?ep.paragraphs.map(p=>'<p class="prose">'+escapeHtml(p)+'</p>').join(''):'<div class="placeholder" role="status">متن این قسمت در مخزن مربوطه موجود نیست.</div>')+'</section><div class="navrow reader-nav" aria-label="'+escapeHtml(label('labels.episodeNavigation','پیمایش قسمت‌ها'))+'"><button class="btn" id="prev-bottom" type="button" aria-label="'+escapeHtml(prevText)+'">'+escapeHtml(prevText)+'</button><button class="btn" id="next-bottom" type="button" aria-label="'+escapeHtml(nextText)+'">'+escapeHtml(nextText)+'</button></div>';
document.getElementById('prev-bottom')?.addEventListener('click',()=>select(activeIndex-1,true));document.getElementById('next-bottom')?.addEventListener('click',()=>select(activeIndex+1,true));}
function applyPageLanguage(){const l=lang();document.documentElement.lang=l;document.documentElement.dir=['fa','ar'].includes(l)?'rtl':'ltr';if(pageTitle)pageTitle.textContent=chapterTitle();if(pageSubtitle)pageSubtitle.textContent={fa:'فصل دوم ظهور در ۱۱ قسمت.',en:'Chapter Two: Emergence in 11 episodes.',ar:'الفصل الثاني: الظهور في 11 حلقة.',zh:'第二章《显现》共 11 章。'}[l];const navLabel={fa:'انتخاب قسمت',en:'Episode selection',ar:'اختيار الحلقة',zh:'选择章节'}[l];document.querySelector('section.controls nav')?.setAttribute('aria-label',navLabel);if(artImage)artImage.alt={fa:'تصویر فصل دوم ظهور',en:'Chapter Two: Emergence artwork',ar:'صورة الفصل الثاني: الظهور',zh:'第二章《显现》插图'}[l];const p={fa:'پیشین',en:'Previous',ar:'السابق',zh:'上一章'}[l],n={fa:'پسین',en:'Next',ar:'التالي',zh:'下一章'}[l],pl={fa:'رفتن به قسمت پیشین',en:'Go to previous episode',ar:'الانتقال إلى الحلقة السابقة',zh:'前往上一章'}[l],nl={fa:'رفتن به قسمت پسین',en:'Go to next episode',ar:'الانتقال إلى الحلقة التالية',zh:'前往下一章'}[l];if(prev){prev.textContent=p;prev.setAttribute('aria-label',pl);}if(next){next.textContent=n;next.setAttribute('aria-label',nl);}if(close)close.setAttribute('aria-label',label('labels.back','بازگشت'));}
function render(){const ep=getLocalizedEpisode(activeIndex),l=lang();document.querySelectorAll('.episode').forEach((b,i)=>{const a=i===activeIndex;b.classList.toggle('active',a);if(a)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.setAttribute('aria-label',({fa:'رفتن به قسمت ',en:'Go to episode ',ar:'الانتقال إلى الحلقة ',zh:'前往第 '}[l]||'Go to episode ')+data.episodes[i].number+({zh:' 章'}[l]||''));});artIndex.textContent=l==='fa'?faNumber(ep.number).padStart(2,'۰')+' / '+faNumber(data.total):String(ep.number).padStart(2,'0')+' / '+data.total;artCaption.textContent=ep.title;renderReader(ep);prev.disabled=activeIndex===0;next.disabled=activeIndex===data.episodes.length-1;}
function select(index,moveFocus=false){if(index<0||index>=data.episodes.length)return;activeIndex=index;render();if(moveFocus)reader.focus({preventScroll:false});}
data.episodes.forEach((episode,index)=>{const b=document.createElement('button');b.type='button';b.className='episode';b.textContent=faNumber(episode.number);b.setAttribute('aria-controls','reader');b.addEventListener('click',()=>select(index));b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();const rtl=document.documentElement.dir==='rtl';let t=index;if(e.key==='Home')t=0;if(e.key==='End')t=data.episodes.length-1;if(e.key==='ArrowRight')t=rtl?index-1:index+1;if(e.key==='ArrowLeft')t=rtl?index+1:index-1;if(t<0)t=data.episodes.length-1;if(t>=data.episodes.length)t=0;select(t,true);});list.appendChild(b);});
prev.addEventListener('click',()=>select(activeIndex-1,true));next.addEventListener('click',()=>select(activeIndex+1,true));close.addEventListener('click',()=>{if(history.length>1)history.back();else window.location.href='index.html';});document.addEventListener('site:languagechange',()=>{applyPageLanguage();render();});applyPageLanguage();render();
})();