/* UI adapter for the shared paragraph workspace. */
(function(){'use strict';
const page=document.getElementById('paragraph-page'), input=document.getElementById('paragraph-input'), count=document.getElementById('paragraph-count'), mode=document.getElementById('paragraph-mode'), action=document.getElementById('paragraph-action'), output=document.getElementById('paragraph-output'), error=document.getElementById('paragraph-error'), source=document.getElementById('paragraph-source'), settings=document.getElementById('paragraph-settings');
const key=document.getElementById('paragraph-api-key'), base=document.getElementById('paragraph-base-url'), model=document.getElementById('paragraph-model'); let entryMode='experience';
function lang(){return window.SiteI18n?.getLanguage?.()||'fa'} function tr(k,f){return window.SiteI18n?.get?.(k,f)||f}
function loadSettings(){const s=window.ParagraphLLM.getSettings();key.value=s.apiKey;base.value=s.baseUrl;model.value=s.model}
function openParagraphPage(kind){entryMode=kind;page.classList.add('open');page.dataset.entry=kind;input.disabled=kind!=='reference';count.disabled=kind!=='experience';mode.disabled=kind!=='experience';action.textContent=tr(kind==='reference'?'paragraphMachine.match':'paragraphMachine.detect',kind==='reference'?'تطبیق':'تشخیص');source.textContent=kind==='reference'?tr('paragraphMachine.referenceSource','متن کاربر → ترجمه به فارسی → سنجش'):tr('paragraphMachine.experienceSource','تولید فارسی → سنجش → ترجمه به زبان سایت');input.value='';output.innerHTML='';error.textContent='';loadSettings();updateDirection()}
function closeParagraphPage(){page.classList.remove('open')}
function updateDirection(){input.dir=(lang()==='fa'||lang()==='ar')?'rtl':'ltr'}
function esc(s){return String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderCard(p,i,text){const proc=window.ParagraphMachineCore.processText(p.text),j=p.judgment;const rows=['S','T','E','R','C'].map(k=>'<tr><td>'+window.ParagraphMachineCore.DOMAIN_NAMES[k]+'</td><td class="pm-status pm-'+j[k].status+'">'+window.ParagraphMachineCore.STATUS_LABELS[j[k].status]+'</td><td>'+esc(j[k].reason)+'</td></tr>').join('');return '<article class="pm-card"><div class="pm-index">'+(i+1)+'</div><div class="pm-text">'+esc(text||proc.text)+'</div><div class="pm-meta"><span>'+proc.finalWordCount+' / 144 '+tr('paragraphMachine.words','کلمه')+'</span><span>'+proc.finalCharCount+' / 900 '+tr('paragraphMachine.chars','حرف')+'</span></div><table><thead><tr><th>'+tr('paragraphMachine.realm','قلمرو')+'</th><th>'+tr('paragraphMachine.status','وضعیت')+'</th><th>'+tr('paragraphMachine.reason','دلیل')+'</th></tr></thead><tbody>'+rows+'</tbody></table></article>'}
async function run(){error.textContent='';output.innerHTML='<div class="pm-loading">'+tr('paragraphMachine.processing','در حال پردازش...')+'</div>';action.disabled=true;try{let results;if(entryMode==='reference'){const raw=input.value.trim();if(!raw)throw new Error(tr('paragraphMachine.empty','متنی وارد نشده است.'));const fa=await window.ParagraphTranslation.toPersian(raw,lang());const p=await window.ParagraphWorkspaceAdapter.evaluatePersian(fa);p._shown=lang()==='fa'?p.text:await window.ParagraphTranslation.fromPersian(p.text,lang());results=[p];source.textContent=tr('paragraphMachine.referenceDone','متن به فارسی منتقل و در هسته سنجیده شد.')}else{results=await window.ParagraphWorkspaceAdapter.generatePersian(Number(count.value),mode.value);for(const p of results)p._shown=lang()==='fa'?p.text:await window.ParagraphTranslation.fromPersian(p.text,lang());source.textContent=tr('paragraphMachine.experienceDone','هسته به فارسی پردازش کرد و خروجی به زبان سایت ترجمه شد.')}output.innerHTML=results.map((p,i)=>renderCard(p,i,p._shown)).join('')}catch(e){error.textContent=e.message||String(e)}finally{action.disabled=false}}
action.addEventListener('click',run);document.getElementById('paragraph-close').addEventListener('click',()=>window.closeParagraph?.());document.getElementById('paragraph-settings-toggle').addEventListener('click',()=>{settings.classList.toggle('collapsed')});document.getElementById('paragraph-save-settings').addEventListener('click',()=>{window.ParagraphLLM.saveSettings({apiKey:key.value.trim(),baseUrl:base.value.trim(),model:model.value.trim()});error.textContent=tr('paragraphMachine.saved','تنظیمات ذخیره شد.')});document.addEventListener('site:languagechange',()=>{updateDirection();if(page.classList.contains('open'))action.textContent=tr(entryMode==='reference'?'paragraphMachine.match':'paragraphMachine.detect',entryMode==='reference'?'تطبیق':'تشخیص')});loadSettings();window.ParagraphPage=Object.freeze({open:openParagraphPage,close:closeParagraphPage});
})();